{
 "title": "Monitoring API Ventes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mémoire process Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de requêtes (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes HTTP / Méthode / Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method, status_code) (http_request_duration_seconds_count)\r\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}